### ISSUE TITLE
Pool dont start on Port 80

### ISSUE THREAD

**Issue by pfreak2000** [Satoex/kawpow-pool#3]
i cant start Pool on http Port 80

**Comment by Satoex** [comment]
hello
you must use this for sato:
stratum+tcp://207.244.250.197:11008
or this for raven 
stratum+tcp://207.244.250.197:10008

why port 80?

**Comment by pfreak2000** [comment]
for the webinterface
if i use port 8800 vor web pool is straing but not on port 80


0|pool  | [2021-10-03T21:42:23.820Z] [error] [system] [init.js] : Master
0|pool  | [2021-10-03T21:42:26.226Z] [info] [system] [Website] : Starting Website module
0|pool  | [2021-10-03T21:42:26.230Z] [info] [system] [Stats] : Starting Stats Module...
0|pool  | [2021-10-03T21:42:26.230Z] [debug] [system] [Stats] : Initializing Stats Redis...
0|pool  | [2021-10-03T21:42:26.233Z] [debug] [system] [Stats] : Initializing Stats History...
0|pool  | [2021-10-03T21:42:26.234Z] [debug] [system] [Website] : Loaded EXAMPLE news_example.html
0|pool  | [2021-10-03T21:42:26.244Z] [info] [system] [Website] : WEBSITE> Attempting to start Website on 0.0.0.0:80
0|pool  | events.js:183
0|pool  |       throw er; // Unhandled 'error' event
0|pool  |       ^
0|pool  | Error: bind EACCES 0.0.0.0:80
0|pool  |     at listenOnMasterHandle (net.js:1420:16)
0|pool  |     at rr (internal/cluster/child.js:121:12)
0|pool  |     at Worker.send (internal/cluster/child.js:88:7)
0|pool  |     at process.onInternalMessage (internal/cluster/utils.js:42:8)
0|pool  |     at emitTwo (events.js:131:20)
0|pool  |     at process.emit (events.js:214:7)
0|pool  |     at emit (internal/child_process.js:762:12)
0|pool  |     at _combinedTickCallback (internal/process/next_tick.js:142:11)
0|pool  |     at process._tickCallback (internal/process/next_tick.js:181:9)
0|pool  | [2021-10-03T21:42:26.257Z] [error] [system] [init.js] : Master
