### ISSUE TITLE
Poll non start

### ISSUE THREAD

**Issue by edcomrocha** [Satoex/kawpow-pool#5]
Hello.
I followed the procedures on this and several other forks in your project.

And everyone has been making the same mistake.
Would you help me ?

pool@kawpow:~/kawpow-pool$ node init.js
/home/pool/kawpow-pool/node_modules/bitcoinjs-lib/src/crypto.js:49
const TAGGED_HASH_PREFIXES = Object.fromEntries(
                                     ^

TypeError: Object.fromEntries is not a function
     at Object.<anonymous> (/home/pool/kawpow-pool/node_modules/bitcoinjs-lib/src/crypto.js:49:37)
     at Module._compile (module.js:653:30)
     at Object.Module._extensions..js (module.js:664:10)
     at Module.load (module.js:566:32)
     at tryModuleLoad (module.js:506:12)
     at Function.Module._load (module.js:498:3)
     at Module.require (module.js:597:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/home/pool/kawpow-pool/node_modules/bitcoinjs-lib/src/payments/p2pkh.js:4:17)
     at Module._compile (module.js:653:30)

Hugs

**Comment by chirunosw** [comment]
seems like bitcoinjs-lib has updated few days ago or the version of nodejs is too low.

**Comment by chirunosw** [comment]
> 

delete this part in /root/kawpow-pool/node_modules/bitcoinjs-lib/src

> const TAGS = [
>   'BIP0340/challenge',
>   'BIP0340/aux',
>   'BIP0340/nonce',
>   'TapLeaf',
>   'TapBranch',
>   'TapSighash',
>   'TapTweak',
>   'KeyAgg list',
>   'KeyAgg coefficient',
> ];
> /** An object mapping tags to their tagged hash prefix of [SHA256(tag) | SHA256(tag)] */
> const TAGGED_HASH_PREFIXES = Object.fromEntries(
>   TAGS.map(tag => {
>     const tagHash = sha256(Buffer.from(tag));
>     return [tag, Buffer.concat([tagHash, tagHash])];
>   }),
> );
> function taggedHash(prefix, data) {
>   return sha256(Buffer.concat([TAGGED_HASH_PREFIXES[prefix], data]));
> }
> exports.taggedHash = taggedHash;

as a noob I can do nothing

**Comment by edcomrocha** [comment]
Latest version of node.js.

I'll try the deletion, thanks for the tip, I'm much more new hahahaha


Hugs

**Comment by BlueCute** [comment]
Hello,
i did try everything but still got this:
renice: failed to set priority for 14603 (process ID): Operation not permitted

**Comment by BartManX** [comment]
How would i fix this ?

/home/pool/kawpow-pool/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/home/pool/kawpow-pool/node_modules/bignum/build/Release/bignum.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/home/pool/kawpow-pool/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/pool/kawpow-pool/node_modules/bignum/index.js:1:92)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
p

Any ideas?
